export interface IUserProfile {
    phone?: string,
    zipCode?: number,
    latitude?: number | null,
    longitude?: number | null,
    businessImageName?: string,
    businessImageId?: string,
    fax?: number | null,
    category?: string,
    subCategory?: string,
    businessUrl?: string,
    streetAddress?: string,
    city?: string,
    state?: string,
    country?: string,
    status?: string,
    error?: string,
    businessId?: string,
    businessName?: string,
    emailAddress?: string,
    imageURL?: any,
    firstName?: string,
    lastName?: string | null,
    businessPlan?:string,
    paypalPaymentId?:string
}